apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: ecommerce
type: Opaque
data:
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: cGtfdGVzdF9mb29fYmFy  # Base64 encoded 'pk_test_foo_bar'
  CLERK_SECRET_KEY: c2tfdGVzdF9mb29fYmFy  # Base64 encoded 'sk_test_foo_bar'
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOjAwMDA@bG9jYWxob3N0L2Vjb21tZXJjZQ==  # Base64 encoded 'postgresql://postgres:0000@localhost/ecommerce'
  # Replace with your actual Sanity project ID, base64 encoded
  NEXT_PUBLIC_SANITY_PROJECT_ID: ZmFrZV9wcm9qZWN0X2lk  # Base64 encoded 'your-actual-project-id'
  # Replace with your actual Sanity API token, base64 encoded
  SANITY_API_READ_TOKEN: ZmFrZV9hcGlfdG9rZW4=  # Base64 encoded 'your-actual-api-token'